### ISSUE TITLE
Baseline Profile not generated

### ISSUE THREAD

**Issue by mlykotom** [android/socialite#17]
The app contains a baseline profile module, but the actual baseline profile wasn't generated, so the app can't benefit from the performance improvements it brings.

**Comment by StylingAndroid** [comment]
There appears to be a bas<img width="1009" alt="baseline-profile" src="https://github.com/android/socialite/assets/ine profile being added to the release build APK.

933874/710f7750-b10a-486a-b8cd-d848733aec3c">

**Comment by StylingAndroid** [comment]
Perhaps you need to generate the BP before building the release APK.

I ran:

` ./gradlew :app:generateReleaseBaselineProfile`

and then rebuilt the release APK. Now I'm seeing both the library profiles and the custom one in the release APK.

<img width="1011" alt="baseline-profile2" src="https://github.com/android/socialite/assets/933874/5a3ce32b-d359-4471-be7a-521e03239d9c">
